services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: dev-users
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
